### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by cheyennejarman** [cheyennejarman/SymbReg_KelpForest#1]
This is for comments and suggestions on my project proposal.

**Comment by varyl97** [comment]
Really cool project proposal Cheyenne! I really like your plan to implement the SCRUM technique - while there might be challenges with implementing this technique for an individual rather than a team I think the process will be really useful for organizing and strategizing your tasks and keeping track of your progress. Sounds great!

**Comment by Medelinkant** [comment]
Really interesting project Cheyenne! Sounds like you will be analyzing lots of data. I think you outline your goals for this course really nicely-- including the implementation of the task organizational technique.

**Comment by ssidder** [comment]
I really enjoyed your presentation, especially the way that you talked about thinking about your decision making process for selecting code. I've never heard of the SCRUM technique and think it would be a good option for organizing my work. I also hadn't ever really thought about reaching out directly to authors of code on their GitHub repo... so your comments around that definitely opened up that as an option for deciphering code. Thanks for sharing your thinking!

**Comment by sielerjm** [comment]
Very interesting project! I have an interest in applying machine learning to microbiome ecological data, so I'll be following your progress keenly. I like the idea of SCRUM you shared. Do you know of any good resources out there to learn more about it?

**Comment by dymite** [comment]
Thank you for your presentation, Cheyenne! I can definitely see how its intimidating to try to understand and execute code that was written by other people / within a different field of study, but I think that you've already done a good job of setting reasonable expectations and achievable goals for yourself in that pursuit. I would love to talk to you more about your experience with computer vision some time - I am interested in potentially employing some of those techniques for analyzing timelapse data of sea otter haul-outs. You rock!

**Comment by maddie-hicks** [comment]
Interesting project and well-done presentation!  That's great that the code that you need is in a public repository so hopefully it'll be easier to communicate with the people who wrote it for clarification.  It would make everyone's life a lot easier if code was public and easy to access!

**Comment by jaredfreedman** [comment]
Great presentation! I really like the idea of implementing the scrum technique to set manageable and motivating deadlines. The whole idea of machine learning is wild to me, so it is very interesting to hear about some of the applications of this to biological research.

**Comment by kjtonra** [comment]
Yay kelp projects!! You obviously have a great background for this type of work and it’s neat to see where you're taking it. The SCRUM implementation technique sounds upper useful too. It’ll be a challenge working with a template from a physics background but if anyone can do it it’s you! Can’t wait to see what you end up accomplishing!

**Comment by cheyennejarman** [comment]
> Thank you for your presentation, Cheyenne! I can definitely see how its intimidating to try to understand and execute code that was written by other people / within a different field of study, but I think that you've already done a good job of setting reasonable expectations and achievable goals for yourself in that pursuit. I would love to talk to you more about your experience with computer vision some time - I am interested in potentially employing some of those techniques for analyzing timelapse data of sea otter haul-outs. You rock!

ooh yes @dymite I would love to talk about that - depending on the format (video or images) there are a few options.

**Comment by cheyennejarman** [comment]
> Very interesting project! I have an interest in applying machine learning to microbiome ecological data, so I'll be following your progress keenly. I like the idea of SCRUM you shared. Do you know of any good resources out there to learn more about it?

There's the site that covers the method well! https://www.digite.com/agile/scrum-methodology/
