### ISSUE TITLE
Project Update

### ISSUE THREAD

**Issue by cheyennejarman** [cheyennejarman/SymbReg_KelpForest#2]
Comments or questions on my update presentation

**Comment by varyl97** [comment]
Hi Cheyenne, great job! I think it's so cool that you were able to reproduce the equation from your advisor without any prior knowledge with your code. It sounds like you're on a great track and making some pretty cool connections among disciplines with your work (physics to ecology).

**Comment by sielerjm** [comment]
I'm impressed with your ability to switch between multiple languages, get your code to work and get the correct equation! Woo!

**Comment by dymite** [comment]
Great work, Cheyenne! It seems like you have been making excellent progress and you should be proud of yourself! I think you will be able to figure out the matlab conversion issue for sure - people say that learning to interpret new programming languages becomes a lot easier once you know one well, so I think you might be surprised by how rapidly you are able to figure it out (:

**Comment by BenjaminDalziel** [comment]
1. Nice work! Congrats on getting this tricking pipeline working and success in the "challenge" that your advisor set!

**Comment by kjtonra** [comment]
I really relate to getting stuck on one thing for a few weeks- glad you had your aha moment! Working through other examples of code on similar data seems like a really good strategy that I should definitely try once I move on to larger datasets. Can't wait to see a talk about your whole project!

**Comment by JustinHockett** [comment]
My knowledge of coding is pretty basic so I was lost for a lot of your presentation but it sounds really cool and you've been making progress so that's great!

**Comment by jaredfreedman** [comment]
Nice job translating the code from MatLab to R, that sounds like a big task!

**Comment by Medelinkant** [comment]
I'm so impressed that you're working in two coding languages. I can really relate to spending lots of time on a coding issue to then later learn what the hiccup was. It's all about the climb :,)

**Comment by maddie-hicks** [comment]
Sounds like you're making great progress, that's awesome that you were able to navigate multiple coding languages and get the output that you wanted!

**Comment by ssidder** [comment]
Congrats on generating the exact equation/results, I bet that feels like a huge step forward. I look forward to learning more about how you are able to get multiple coding languages to "sing" together as the term progresses and you share more of your project with the class.
